### PR TITLE
Adding Assignment and Homework

### PR DESCRIPTION
**Pull request by snmudunuri**
Assignment and Homework for class 3 are added.

### CODE REVIEW

**Review by Kilavagora — CHANGES_REQUESTED** [review]
By camerlCase convention variable name should be **dateOfBirth**, **numOfMonth** and etc.

Instead of switch, can you try to make your getZodiac use two arrays and a single if else? 

Also, why Chinese zodiac is limited to years after 1924? It should work for all years.

**Comment by snmudunuri** [comment]
@Kilavagora Wikipedia link that shared shows 1924 as first year for Zodiac sign and so I took that as reference for this.

**Comment by Kilavagora** [comment]
> @Kilavagora Wikipedia link that shared shows 1924 as first year for Zodiac sign and so I took that as reference for this.

Chinese new year does not have a fixed start date, that why there is the table. But for the purpose of this assignment we care only about what sign the most of the year is.

**Comment by snmudunuri** [comment]
> > @Kilavagora Wikipedia link that shared shows 1924 as first year for Zodiac sign and so I took that as reference for this.
> 
> Chinese new year does not have a fixed start date, that why there is the table. But for the purpose of this assignment we care only about what sign the most of the year is.

@Kilavagora I made those changes to accept any year. To get astrological sign, you said use only one if else, does that mean just one if and one else with no  if else inside the first if?

**Comment by snmudunuri** [comment]
@Kilavagora Can I use multiple else if conditions to get the Zodiac or just one if else?

**Comment by Kilavagora** [comment]
> @Kilavagora I made those changes to accept any year. To get astrological sign, you said use only one if else, does that mean just one if and one else with no if else inside the first if?

Correct. Only a single if else. Actually, you do not even need **else**, since you are defining a function and you can return.

**Comment by snmudunuri** [comment]
> > @Kilavagora I made those changes to accept any year. To get astrological sign, you said use only one if else, does that mean just one if and one else with no if else inside the first if?
> 
> Correct. Only a single if else. Actually, you do not even need **else**, since you are defining a function and you can return.

@Kilavagora I made the changes as you said but now while committing new changes, my new files for class 4 are also added to this branch. How can I revert that and push just these changes?

**Comment by snmudunuri** [comment]
@Kilavagora Ignore my previous question. I fixed that and pushed changes as per your suggestion

**Review by Kilavagora — CHANGES_REQUESTED** [review]
You are missing variable declaration statements.

Use **const**. That should be the default choice :)

Change last_day to lastDay, dateofBirth to dateOfBirth, numofHours to numOfHours. 

Also you can remove the last else statement. It is redundant, since you are returning from the function. Just 

```javascript
     if (dateofBirth + 1 > last_day[month]) {
          return zodiac[month + 1];
        }
     return zodiac[month];
```

will do. Also it is very interesting that if you enter a date in mm/dd/yyyy format it does not work for bordering dates :)

**Review by Kilavagora — APPROVED** [review]
👍

**Pull request merged**
