### PR TITLE
Class 1 local branch

### PR DESCRIPTION
**Pull request by snmudunuri**
Home Work for Class_1

### CODE REVIEW

**Comment by Kilavagora** [comment]
@snmudunuri 
- Sync your master branch with upstream first, the pull request for homework should only have homework changes.
- To avoid merge conflicts (In case I change class 1 files), keep original files intact. Instead create a copy as e.g. homework.html where you can separately have your changes.
- Monday is missing "y" :P
- We will learn about coding style later, but you need spaces after commas in the Array arguments.
- Also in most of the style guides will have a preference for quotations. So it's better to use single quotes everywhere, or double quotes everywhere.

**Comment by snmudunuri** [comment]
@Kilavagora

So, do you want me to re-do this now following the steps
1. create a local branch
2. create homework.html
3. commit, push,
4. pull request.


Is that correct?

**Comment by snmudunuri** [comment]
@Kilavagora Also, do you want me to close this pull request?

**Comment by Kilavagora** [comment]
@snmudunuri 
First, sync your master with upstream. This part does not need a separate branch :)

In general, you fix issues in the branch you made pull request from. You can just return the original sample.html and rename your sample.html to homework.html and push to the current branch. In this case you don't need to make a new pull request. Changes will be updated automatically. 

But if it is easier for you, you can make a new branch, push to it and make a new pull request instead.

**Comment by snmudunuri** [comment]
@Kilavagora Can you check this now?

**Pull request merged**
